# Generated by Django 4.1 on 2022-09-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentRooms',
        ),
    ]
