# Generated by Django 4.1 on 2022-09-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_recentrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentrooms',
            name='is_friend',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
