# Generated by Django 4.1 on 2022-08-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
