# Generated by Django 4.1 on 2022-09-07 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_remove_friendrequest_time_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
