# Generated by Django 4.1 on 2022-09-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_friendrequest_time_stamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='time_stamp',
        ),
    ]
